// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb06CMJ1p-3DSUKe2UgpRpwZLFv3ia9ok',
    appId: '1:433368136843:android:328b09becd84e58030a88e',
    messagingSenderId: '433368136843',
    projectId: 'rickandmortyapi-d5e6d',
    storageBucket: 'rickandmortyapi-d5e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5IqxhRnM0R5GM8wAbsZ2BoCZ_9WLunfs',
    appId: '1:433368136843:ios:df1a31def1cbf48430a88e',
    messagingSenderId: '433368136843',
    projectId: 'rickandmortyapi-d5e6d',
    storageBucket: 'rickandmortyapi-d5e6d.firebasestorage.app',
    iosClientId: '433368136843-hn5a3v9srlhefirerldmvpv97rbki8br.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFinal',
  );

}